# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "69be8548ba370a7830eb472fc66efc02"
name = "replix-ai"
application_url = "https://replix-ai-black.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [webhooks.privacy_compliance]
  customer_data_request_url = "/webhooks/customers/data_request"
  customer_deletion_url = "/webhooks/customers/redact"
  shop_deletion_url = "/webhooks/shop/redact"

[auth]
redirect_urls = [ "https://replix-ai-black.vercel.app/api/auth", "https://replix-ai-black.vercel.app/auth/callback", "https://replix-ai-black.vercel.app/auth/shopify/callback" ]

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://replix-ai-black.vercel.app/api/proxy"
subpath = "replix"
prefix = "apps"
